# Generated by Django 3.2.16 on 2022-12-04 16:11

import chat.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.ImageField(blank=True, upload_to=chat.models.user_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
