# Generated by Django 3.2.16 on 2022-12-04 16:28

import chat.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20221204_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to=chat.models.user_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
