# Generated by Django 3.2.16 on 2022-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='audio_src',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
